### ISSUE TITLE
Create minimum set of archive services on a single host

### ISSUE THREAD

**Issue by januo-io** [januo-org/proof-of-concepts#141]
1. https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker
2. https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql#environment-variables
3. https://sourceforge.net/projects/dcm4che/files/Weasis/weasis-pacs-connector/7.1.2/

**Comment by januo-io** [comment]
@fourtimes https://github.com/dcm4che/dcm4chee-arc-light/wiki/Run-minimum-set-of-archive-services-on-a-single-host

**Comment by januo-io** [comment]
Architecture



![Image](https://github.com/januo-org/proof-of-concepts/assets/57703276/1e789734-37d6-44e1-84cd-b7718adb6deb)

**Comment by januo-io** [comment]
installation process

```bash
docker network create dcm4chee_network
docker run --network=dcm4chee_network --name ldap \
           -p 389:389 \
           -v /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data \
           -v /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d \
           -d dcm4che/slapd-dcm4chee:2.6.5-31.1
```

**Comment by januo-io** [comment]
If you want create test DICOM image use below command

docker run --rm --network=dcm4chee_network dcm4che/dcm4che-tools storescu -cDCM4CHEE@192.168.1.94:11112 /opt/dcm4che/etc/testdata/dicom

**Comment by januo-io** [comment]
oauth-proxy have some issue.

**Comment by januo-io** [comment]
https://github.com/dcm4che-dockerfiles/dcm4chee-arc-psql#deploy-additional-applications

how to build the weasis

**Comment by januo-io** [comment]
@rio-ke 

```yml
version: "3"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.6.5-31.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    environment:
      STORAGE_DIR: /storage/fs1
    volumes:
      - /var/local/dcm4chee-arc/ldap:/var/lib/openldap/openldap-data
      - /var/local/dcm4chee-arc/slapd.d:/etc/openldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:15.4-31
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.31.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "9993:9993"
      - "11112:11112"
      - "2762:2762"
      - "2575:2575"
      - "12575:12575"
    environment:
      POSTGRES_DB: pacsdb
      POSTGRES_USER: pacs
      POSTGRES_PASSWORD: pacs
      WILDFLY_CHOWN: /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /var/local/dcm4chee-arc/storage:/storage
```

Can you please explain  this file @januo-io @rio-ke @fourtimes
