### ISSUE TITLE
Installation of Keycloak on Docker.

### ISSUE THREAD

**Issue by januo-io** [januo-org/proof-of-concepts#142]

**Comment by januo-io** [comment]
I have started the process of Keycloak integration. In the future, if someone wants to integrate the single sign-on process with their application, this is the best solution. It is an open-source project that will help us manage the apps to log in with the help of single sign-on.

**Comment by januo-io** [comment]
development keycloak docker running images

```console
docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin \ 
quay.io/keycloak/keycloak:23.0.3 start-dev
```

**Comment by fourtimes** [comment]
@januo-io 

I have work down **Keycloak** docker container using docker compose file. These are the below docker compose file for creating a Keycloak docker container. The file name should be -  `docker-compose.yml`
```yml
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
        #      - KEYCLOAK_FRONTEND_URL=https://dcm4che.januo.io/
        #      - KEYCLOAK_BASE_URL=https://dcm4che.januo.io/
      - PROXY_ADDRESS_FORWARDING=true
      - DEBUG=true
      - DEBUG_PORT='*:8787'
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=DEBUG
      - JAVA_OPTS=-server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - dcm4che

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"
    networks:
      - dcm4che
    volumes:
      - /var/local/dcm4che/db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "1"
          memory: 512M
networks:
  dcm4che:
    name: dcm4che
    driver: bridge
```
OUTPUT
----
![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/55a224eb-e1a4-498a-b605-687aa1678beb)

![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/445d342e-c6c6-404b-969d-8aa880f7e87e)

![Image](https://github.com/januo-org/proof-of-concepts/assets/91359308/36017c56-5eb6-4913-9a12-450ae3a24112)
